### ISSUE TITLE
ERROR Uncaught Exception in Thread

### ISSUE THREAD

**Issue by Jaykah** [danilop/yas3fs#107]
Recently I started getting the following error when running yas3fs in debug:
```
2015-09-25 18:18:22,780 DEBUG Got 10 messages from SQS
2015-09-25 18:18:22,780 ERROR Uncaught Exception in Thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2894, in run
    super(TracebackLoggingThread, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 1139, in listen_for_messages_over_sqs
    message = content['Message'].encode('ascii')
KeyError: 'Message'
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2894, in run
    super(TracebackLoggingThread, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 1139, in listen_for_messages_over_sqs
    message = content['Message'].encode('ascii')
KeyError: 'Message'
```

Can anyone shed any light as to why this might be happening?

**Comment by Jaykah** [comment]
Update:

On another node the error is a bit different:

```
2015-09-28 17:58:45,130 ERROR Uncaught Exception in Thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2894, in run
    super(TracebackLoggingThread, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 1140, in listen_for_messages_over_sqs
    self.process_message(message)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 1172, in process_message
    if c[0] == self.unique_id:
KeyError: 0
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2894, in run
    super(TracebackLoggingThread, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 1140, in listen_for_messages_over_sqs
    self.process_message(message)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 1172, in process_message
    if c[0] == self.unique_id:
KeyError: 0
```


I also tried upgrading to Python 2.7.10 as well as downgrading to 2.6.2, neither helped.

**Comment by Jaykah** [comment]
So it looks like the message arrives (in unicode), but then the json is not getting parsed properly


This is the string (obfuscated):
```
{
    u'SignatureVersion': u'1',
    u'Timestamp': u'2015-09-25T21: 26: 12.750Z',
    u'Signature': u'long signature here==',
    u'SigningCertURL': u'https: //sns.us-east-1.amazonaws.com/SimpleNotificationService-longidhere.pem',
    u'MessageId': u'91d4556c-9faa-588a-8336-1b13219ea33a',
    u'Message': u'{
        "Records": [
            {
                "eventVersion": "2.0",
                "eventSource": "aws:s3",
                "awsRegion": "us-east-1",
                "eventTime": "2015-09-25T21:26:12.708Z",
                "eventName": "ObjectCreated:Copy",
                "userIdentity": {
                    "principalId": "AWS:AIDAJSJSDAAAAAAAAAW"
                },
                "requestParameters": {
                    "sourceIPAddress": "222.101.133.222"
                },
                "responseElements": {
                    "x-amz-request-id": "9E6B39B6C270AAAA",
                    "x-amz-id-2": "long signature here="
                },
                "s3": {
                    "s3SchemaVersion": "1.0",
                    "configurationId": "push",
                    "bucket": {
                        "name": "mybucket",
                        "ownerIdentity": {
                            "principalId": "A2D3SQ3NGL84AA"
                        },
                        "arn": "arn:aws:s3:::mybucket"
                    },
                    "object": {
                        "key": "zookeeper.rb",
                        "size": 7468,
                        "sequencer": "005605BBF49D43AABA"
                    }
                }
            }
        ]
    }',
    u'UnsubscribeURL': u'https: //sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn: aws: sns: us-east-1: 7416545093333: myid: 77c77ca4-0d8c-412b-af46-734503555552',
    u'Type': u'Notification',
    u'TopicArn': u'arn: aws: sns: us-east-1: 7416545093333: myid',
    u'Subject': u'AmazonS3Notification'
}
```


but then we get:

```
KeyError: 'Message'
```

Does that look like an issue with json.loads()?

**Comment by Jaykah** [comment]
Ok, it looks like it's not able to grab 'Message' from the dictionary:

```
print "message full", content.get('Message')
```

returns 

```
message full None
```

**Comment by danilop** [comment]
Did you enable S3 Event notification on the Bucket? YAS3FS was designed before that functionality was available and generates its own events publishing to SNS from the nodes.

**Comment by Jaykah** [comment]
@danilop I experimented with a variety of settings, but disabling bucket notifications did not help, unfortunately.
