### ISSUE TITLE
--cache-on-disk option prevents file data to be uploaded

### ISSUE THREAD

**Issue by grikdotnet** [danilop/yas3fs#112]
Hi, I am mounting a bucket with a command
```
$ yas3fs -df s3://sdamtest/ $(pwd)/s3mount/ --cache-path $(pwd)/s3cache/ --cache-on-disk 10240
```
If I copy any non-empty file to the mounted folder, I get an error
```
~$ cp 1.txt s3mount/
cp: error writing ‘s3mount/1.txt’: Bad address
cp: failed to extend ‘s3mount/1.txt’: Bad address
```
The files are created in a bucket, but they are empty.

The debug mode log shows errors:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 414, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 515, in write
    offset, fh)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 881, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2560, in write
    logger.debug("write '%s' '%i' '%i' '%s' '%s' content" % (path, len(new_data), offset, fh, data.content.name.decode('utf-8')))
AttributeError: '_io.BytesIO' object has no attribute 'name'
```

The full log is here: http://pastebin.com/aNkUXpjd

**Comment by grikdotnet** [comment]
when the FS is unmounted the error is
```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):Exception in thread Thread-17 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2901, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exception'

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2901, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exception'
```

**Comment by dougbyrne** [comment]
I'm sorry to post just a 'me too' but I'm seeing the same issue with the same log entries. I'm removing the parameter as a workaround for now.

**Comment by KasperMadsen** [comment]
I am also seeing this :)

**Comment by robparrott** [comment]
Also seeing this ...
