### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by joelgriffiths** [danilop/yas3fs#16]
Is this something to be concerned about? I'm using 1.0.15 for now because the 2.x will require more retrofitting than I was prepared to do in the chef recipes.

2014-04-03 20:05:40,603 INFO entries, mem_size, disk_size, download_queue, prefetch_queue: 192, 0, 7334593, 0, 0
2014-04-03 20:05:44,103 ERROR [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/yas3fs/yas3fs", line 1911, in flush
    k.set_contents_from_file(data.content, headers={'Content-Type': mimetype})
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1246, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 725, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 914, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 571, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 907, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 815, in sender
    http_conn.send(chunk)
  File "/usr/lib/python2.7/httplib.py", line 790, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/ssl.py", line 229, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 198, in send
    v = self._sslobj.write(data)
error: [Errno 104] Connection reset by peer
2014-04-03 20:05:45,104 INFO flush '/internal_attachments/1836/1836021-002ced50f265b00f6002a5783ea6bc73.data' '0' '<Key: firefall-forum-data,internal_attachments/1836/1836021-002ced50f265b00f6002a5783ea6bc73.data>' 'application/octet-stream' S3 retry 1
2014-04-03 20:05:45,604 INFO entries, mem_size, disk_size, download_queue, prefetch_queue: 193, 0, 7334593, 0, 0
2014-04-03 20:05:50,605 INFO entries, mem_size, disk_size, download_queue, prefetch_queue: 195, 0, 7334593, 0, 0

**Comment by robmoore** [comment]
I'm seeing the connection reset by peer error that looks similar. Just curious if there's any retry logic in case of such a error.

```
2015-03-30 07:14:41,939 ERROR set_contents_from_file IOError on <yas3fs.FSData instance at 0x7f56ec1f0ea8>
2015-03-30 07:14:41,939 ERROR [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2091, in do_cmd_on_s3_now
    raise e
error: [Errno 104] Connection reset by peer
2015-03-30 08:30:52,160 ERROR set_contents_from_file IOError on <yas3fs.FSData instance at 0x2bf13f8>
2015-03-30 08:30:52,160 ERROR [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2091, in do_cmd_on_s3_now
    raise e
error: [Errno 104] Connection reset by peer
2015-03-30 08:33:20,951 ERROR set_contents_from_file IOError on <yas3fs.FSData instance at 0x7f56f8046b00>
2015-03-30 08:33:20,951 ERROR [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2091, in do_cmd_on_s3_now
    raise e
error: [Errno 104] Connection reset by peer
2015-03-30 08:33:23,784 ERROR set_contents_from_file IOError on <yas3fs.FSData instance at 0x7f56ec1ef680>
2015-03-30 08:33:23,784 ERROR [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 2091, in do_cmd_on_s3_now
    raise e
error: [Errno 104] Connection reset by peer
```

**Comment by bitsofinfo** [comment]
yes they should be retried, despite being logged, see options `s3_retries_sleep` and `download_retries_num`

**Comment by robmoore** [comment]
@bitsofinfo Thanks!

**Comment by bitsofinfo** [comment]
no problem
