### ISSUE TITLE
Unable to `pip install yas3fs` on Ubuntu server

### ISSUE THREAD

**Issue by DavidGarciaCat** [danilop/yas3fs#193]
Hey there,

I am getting the same output either with `sudo` and without it:

```
$ sudo pip install yas3fs
Collecting yas3fs
  Using cached yas3fs-2.3.5.tar.gz (38 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-otiy1296/yas3fs/setup.py'"'"'; __file__='"'"'/tmp/pip-install-otiy1296/yas3fs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-otiy1296/yas3fs/pip-egg-info
         cwd: /tmp/pip-install-otiy1296/yas3fs/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-otiy1296/yas3fs/setup.py", line 5, in <module>
        execfile('yas3fs/_version.py')
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I guess this is related to #191 and #192 but I can't see any activity on this repo since around half a year ago by now?

Cheers,

**Comment by jazzl0ver** [comment]
pip is no longer supported. install using git clone

**Comment by DavidGarciaCat** [comment]
I'm not used to python and the readme does not have a step-by-step guide

Can you please tell me what commands I should use?

**Comment by jazzl0ver** [comment]
Locate CentOS section in the readme
