### ISSUE TITLE
[SOLVED] uncaught exception / folder not accessible in linux

### ISSUE THREAD

**Issue by gianlucanigro** [danilop/yas3fs#78]
Hi,

in my logs I got a lot of this

2014-12-10 02:59:48,592 DEBUG Got 1 messages from SQS
2014-12-10 02:59:48,593 DEBUG process_message '["213ab7c6-9055-453e-9170-afcfc34a74e8", "upload", "/clienti/opportunity/IN/nominativi.xls"]'
2014-12-10 02:59:48,593 ERROR Uncaught Exception in Thread
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/yas3fs/__init__.py", line 2392, in run
    super(TracebackLoggingThread, self).run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/yas3fs/__init__.py", line 932, in listen_for_messages_over_sqs
    self.process_message(message)
  File "/usr/lib/python2.6/site-packages/yas3fs/__init__.py", line 972, in process_message
    self.invalidate_cache(c[2], c[3])
IndexError: list index out of range

my scenario is the following

3 ec2 instances sharing a bucket and using SQS to process messages, on two of them during the night two folders which are heavily accessed by the third instance become inaccessible 

if you try to ls them you got only questions mark (see https://dl.dropboxusercontent.com/u/36103215/yas3fs_error.png)

After  I send a reset messages thru SNS everything is OK... maybe the two instances are overwhelmed by the changes made by the third?

TIA for any idea

ps I have the whole log here http://www2.gianlucanigro.eu/yas3fs.log.gz

**Comment by gianlucanigro** [comment]
Actually it was a timing problem... the file got unlinked quite fast and the other nodes received messages from the SNS topic in the wrong order, first the unlink and after the upload

Just adding a pause of a few seconds between the creation and the deletion of file solved the problem
