### ISSUE TITLE
CentOS 7 cannot import name FUSE

### ISSUE THREAD

**Issue by cdenneen** [danilop/yas3fs#97]
```
# yas3fs s3://my-bucket-artifacts/ /mnt/s3
Traceback (most recent call last):
  File "/usr/bin/yas3fs", line 9, in <module>
    load_entry_point('yas3fs==2.3.2', 'console_scripts', 'yas3fs')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/yas3fs/__init__.py", line 42, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn, fuse_get_context
ImportError: cannot import name FUSE
```

**Comment by danilop** [comment]
Hi, just to be sure: did you install FUSE at OS level and fusepy for Python?
I mean:
yum install fuse
pip install -U fusepy

**Comment by derchrisuk** [comment]
And as a reminder, if you have fuse-python installed from the OS repo, it needs to be removed.
Otherwise it will not work.

**Comment by fdutheil** [comment]
Thanks to your help, here is the procedure to get yas2fs working on RHEL/CentOS (tested on 6.x):
```
yum install python-pip fuse fuse-libs
pip install yas3fs
pip install -U fusepy
```
